services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/dangtran/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/dangtran/data/mysql
      o: bind

networks:
  inception:
    name: inception
